<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-23T14:56:53 IST" name="Suite" finished-at="2025-07-23T14:57:06 IST" duration-ms="13234">
    <groups>
    </groups>
    <test started-at="2025-07-23T14:56:53 IST" name="Regression" finished-at="2025-07-23T14:57:06 IST" duration-ms="12509">
      <class name="BooksScrape.Test.BooksScrapeFunctionalTest">
        <test-method is-config="true" signature="getApplication()[pri:0, instance:BooksScrape.Test.BooksScrapeFunctionalTest@194fad1]" started-at="2025-07-23T14:56:53 IST" name="getApplication" finished-at="2025-07-23T14:57:00 IST" duration-ms="6418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplication -->
        <test-method signature="BookApplication()[pri:0, instance:BooksScrape.Test.BooksScrapeFunctionalTest@194fad1]" started-at="2025-07-23T14:57:00 IST" name="BookApplication" finished-at="2025-07-23T14:57:06 IST" duration-ms="5949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BookApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:BooksScrape.Test.BooksScrapeFunctionalTest@194fad1]" started-at="2025-07-23T14:57:06 IST" name="tearDown" finished-at="2025-07-23T14:57:06 IST" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BooksScrape.Test.BooksScrapeFunctionalTest -->
    </test> <!-- Regression -->
    <test started-at="2025-07-23T14:56:53 IST" name="ErrorValidation" finished-at="2025-07-23T14:57:06 IST" duration-ms="13234">
      <class name="BooksScrape.Test.ErrorValidation">
        <test-method is-config="true" signature="getApplication()[pri:0, instance:BooksScrape.Test.ErrorValidation@710c2b53]" started-at="2025-07-23T14:56:53 IST" name="getApplication" finished-at="2025-07-23T14:57:00 IST" duration-ms="6352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplication -->
        <test-method retried="true" signature="PageHeaderValidation()[pri:0, instance:BooksScrape.Test.ErrorValidation@710c2b53]" started-at="2025-07-23T14:57:00 IST" name="PageHeaderValidation" finished-at="2025-07-23T14:57:01 IST" duration-ms="1408" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Page Header is science, explicitly failing this Test. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Page Header is science, explicitly failing this Test. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at BooksScrape.Test.ErrorValidation.PageHeaderValidation(ErrorValidation.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageHeaderValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:BooksScrape.Test.ErrorValidation@710c2b53]" started-at="2025-07-23T14:57:01 IST" name="tearDown" finished-at="2025-07-23T14:57:01 IST" duration-ms="107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="getApplication()[pri:0, instance:BooksScrape.Test.ErrorValidation@710c2b53]" started-at="2025-07-23T14:57:01 IST" name="getApplication" finished-at="2025-07-23T14:57:05 IST" duration-ms="3460" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplication -->
        <test-method signature="PageHeaderValidation()[pri:0, instance:BooksScrape.Test.ErrorValidation@710c2b53]" started-at="2025-07-23T14:57:05 IST" name="PageHeaderValidation" finished-at="2025-07-23T14:57:06 IST" duration-ms="1416" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Page Header is science, explicitly failing this Test. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Page Header is science, explicitly failing this Test. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at BooksScrape.Test.ErrorValidation.PageHeaderValidation(ErrorValidation.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageHeaderValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:BooksScrape.Test.ErrorValidation@710c2b53]" started-at="2025-07-23T14:57:06 IST" name="tearDown" finished-at="2025-07-23T14:57:06 IST" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BooksScrape.Test.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
