<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-23T14:39:00 IST" name="Suite" finished-at="2025-07-23T14:39:13 IST" duration-ms="12979">
    <groups>
    </groups>
    <test started-at="2025-07-23T14:39:00 IST" name="ErrorValidation" finished-at="2025-07-23T14:39:13 IST" duration-ms="12979">
      <class name="BooksScrape.Test.ErrorValidation">
        <test-method is-config="true" signature="getApplication()[pri:0, instance:BooksScrape.Test.ErrorValidation@7dfd3c81]" started-at="2025-07-23T14:39:00 IST" name="getApplication" finished-at="2025-07-23T14:39:06 IST" duration-ms="6114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplication -->
        <test-method retried="true" signature="PageHeaderValidation()[pri:0, instance:BooksScrape.Test.ErrorValidation@7dfd3c81]" started-at="2025-07-23T14:39:06 IST" name="PageHeaderValidation" finished-at="2025-07-23T14:39:07 IST" duration-ms="1391" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Page Header is science, explicitly failing this Test. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Page Header is science, explicitly failing this Test. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at BooksScrape.Test.ErrorValidation.PageHeaderValidation(ErrorValidation.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageHeaderValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:BooksScrape.Test.ErrorValidation@7dfd3c81]" started-at="2025-07-23T14:39:07 IST" name="tearDown" finished-at="2025-07-23T14:39:07 IST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="getApplication()[pri:0, instance:BooksScrape.Test.ErrorValidation@7dfd3c81]" started-at="2025-07-23T14:39:07 IST" name="getApplication" finished-at="2025-07-23T14:39:11 IST" duration-ms="3632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplication -->
        <test-method signature="PageHeaderValidation()[pri:0, instance:BooksScrape.Test.ErrorValidation@7dfd3c81]" started-at="2025-07-23T14:39:11 IST" name="PageHeaderValidation" finished-at="2025-07-23T14:39:12 IST" duration-ms="1315" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Page Header is science, explicitly failing this Test. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Page Header is science, explicitly failing this Test. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at BooksScrape.Test.ErrorValidation.PageHeaderValidation(ErrorValidation.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageHeaderValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:BooksScrape.Test.ErrorValidation@7dfd3c81]" started-at="2025-07-23T14:39:13 IST" name="tearDown" finished-at="2025-07-23T14:39:13 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BooksScrape.Test.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
